WINDOW_WIDTH = 1200
WINDOW_HEIGHT = 800
FPS = 60
APP_NAME ="Reinforcement Learning Simulation"

SMALL_BUTTON_DIMENSIONS = [80, 80]
LARGE_BUTTON_DIMENSIONS = [200, 80]

UI_BONE_WIDTH = 13
UI_MUSCLE_WIDTH = 23

# neural network screen
W_SPACING_NEURONS = 70
H_SPACING_NEURONS = 10
RADIUS_NEURONS = 16