WINDOW_WIDTH = 1200
WINDOW_HEIGHT = 800
FPS = 60
APP_NAME ="Reinforcement Learning Simulation"

SMALL_BUTTON_DIMENSIONS = [80, 80]
LARGE_BUTTON_DIMENSIONS = [200, 80]

UI_BONE_WIDTH = 13
UI_MUSCLE_WIDTH = 23

SAVE_FILE_PATH = "./data/"
ASSETS_PATH = "./assets/"

# neural network screen
W_SPACING_NEURONS = 70
H_SPACING_NEURONS = 10
RADIUS_NEURONS = 16

# simulation
SIMULATION_BONE_WIDTH = 10.0
BODY_FRICTION = 1.0
BODY_MASS = 0.8
OVERLAP_ALLOWED = True
SCALE = 10
MOTOR_MAX_FORCE = 4e6
MOTOR_AMPLITUDE = 2.2
SIMULATION_SUBSTEPS = 5