WINDOW_WIDTH = 1200
WINDOW_HEIGHT = 800
FPS = 60
APP_NAME ="Reinforcement Learning Simulation"

SMALL_BUTTON_DIMENSIONS = [80, 80]
LARGE_BUTTON_DIMENSIONS = [200, 80]

UI_BONE_WIDTH = 13
UI_MUSCLE_WIDTH = 23

SAVE_FILE_PATH = "./data/"
ASSETS_PATH = "./assets/"

# neural network screen
W_SPACING_NEURONS = 70
H_SPACING_NEURONS = 10
RADIUS_NEURONS = 16

# simulation
SIMULATION_BONE_WIDTH = 10.0
BODY_FRICTION = 1.0
BODY_MASS = 0.8
OVERLAP_ALLOWED = True
JOINT_LIMITS = True
SCALE = 15
MOTOR_MAX_FORCE = 4e6
SIMULATION_SUBSTEPS = 30
MAX_JOINT_ANGLE = 30 # degrees
MIN_JOINT_ANGLE = 2
ADD_SPRINGS = False
GROUND_Y = 700
GRAVITY = 1200
GROUND_FRICTION = 1.0
MAX_MOTOR_RATE = 15
EXPECTED_MAX_ANGULAR_VELOCITY = 15 #? trbalo bi da se testira i proveri sluzi za normalizaciju
EXPECTED_MAX_LINEAR_VELOCITY = 15

# training
NUM_OF_STEPS_PER_EPISODE = 540 # 18s vizuelno
NUM_OF_EPIOSDES_PER_SIMULATION = 500
STOP_AT_SIMULATION_END = False